Repository Soongsil-CoffeeChat/COGO-DEV-app, pull requests merged in 2024-11, with the labels that each got.

#43 [Feature/#42] 검색버튼 삭제
  ios/Runner.xcodeproj/project.pbxproj
  lib/common/widgets/atoms/texts/styles.dart
  lib/data/di/api_client.dart
  lib/data/dto/response/mentor_detail_response.dart
  lib/data/dto/response/mentor_part_response.dart
  lib/data/service/mentor_service.dart
  lib/features/home/home/view/home_screen.dart
  lib/features/home/home/view_model/home_view_model.dart
  lib/features/home/profile/model/profile_detail_item.dart
  lib/features/home/profile/view/profile_detail_screen.dart
  lib/features/home/profile/view_model/profile_detail_view_model.dart
  lib/features/home/search/view/search_screen.dart
  lib/features/home/search/view_model/search_view_model.dart
Labels: feature

#44 [Feature/#41] 파트로 멘토리스트 검색 api
  lib/common/widgets/profile_card.dart
  lib/constants/apis.dart
  lib/data/dto/response/mentor_detail_response.dart
  lib/data/dto/response/mentor_part_response.dart
  lib/data/service/mentor_service.dart
  lib/domain/entity/mentor_detail_entity.dart
  lib/domain/entity/mentor_part_entity.dart
  lib/features/home/home/view/home_screen.dart
  lib/features/home/home/view_model/home_view_model.dart
  lib/features/home/profile/view/profile_detail_screen.dart
  lib/features/home/profile/view_model/profile_detail_view_model.dart
  lib/features/home/search/view_model/search_view_model.dart
  lib/main.dart
  lib/route/routes.dart
Labels: feature

#48 [Design/#47] home, cogo 디자인 수정
  lib/common/widgets/custom_box.dart
  lib/common/widgets/custom_button.dart
  lib/common/widgets/date_picker.dart
  lib/common/widgets/header.dart
  lib/common/widgets/horizontal_button_list.dart
  lib/common/widgets/horizontal_date_picker.dart
  lib/common/widgets/mentor_profile_dialog.dart
  lib/common/widgets/profile_card.dart
  lib/common/widgets/time_picker.dart
  lib/common/widgets/widgets.dart
  lib/features/cogo/views/mentee/cogo_screen.dart
  lib/features/cogo/views/mentee/sended_cogo_detail_screen.dart
  lib/features/cogo/views/mentee/sended_cogo_screen.dart
  lib/features/cogo/views/mentee/successed_cogo_detail_screen.dart
  lib/features/cogo/views/mentee/successed_cogo_screen.dart
  lib/features/cogo/views/mentor/cogo_screen.dart
  lib/features/cogo/views/mentor/received_cogo_detail_screen.dart
  lib/features/cogo/views/mentor/received_cogo_screen.dart
  lib/features/cogo/views/mentor/successed_cogo_detail_screen.dart
  lib/features/cogo/views/mentor/successed_cogo_screen.dart
  lib/features/home/apply/view_models/memo_view_model.dart
  lib/features/home/apply/view_models/schedule_view_model.dart
  lib/features/home/apply/views/matching_screen.dart
  lib/features/home/apply/views/memo_screen.dart
  lib/features/home/apply/views/schedule_screen.dart
  lib/features/home/home/view/home_screen.dart
  lib/features/home/profile/view/profile_detail_screen.dart
  lib/route/routes.dart
Labels: Design

#49 [Feature] 멘토 자기소개 입력 api 연동
  lib/constants/apis.dart
  lib/data/dto/response/mentor_introduction_response.dart
  lib/data/service/mentor_service.dart
  lib/features/home/mentor_detail/view_models/mentor_introduction_view_model.dart
Labels: feature

#52 [Fix/#51] mentor detail screen null 오류 수정
  lib/data/service/mentor_service.dart
  lib/domain/entity/mentor_detail_entity.dart
  lib/features/home/profile/view/profile_detail_screen.dart
  lib/features/home/profile/view_model/profile_detail_view_model.dart
  lib/route/routes.dart
Labels: fix

#55 [Feature/#54] 커피쳇 가능 시간 불러오기 api
  lib/common/widgets/time_picker.dart
  lib/data/dto/response/mentor_possible_date_response.dart
  lib/data/service/possibledate_service.dart
  lib/domain/entity/mentor_possible_date_entity.dart
  lib/features/home/apply/view_models/schedule_view_model.dart
  lib/features/home/apply/views/schedule_screen.dart
  lib/features/home/home/view_model/home_view_model.dart
  lib/features/home/profile/view/profile_detail_screen.dart
  lib/features/home/profile/view_model/profile_detail_view_model.dart
  lib/route/routes.dart
Labels: feature

#53 [Feature/#50] COGO 신청 api
  assets/icons/3d_img/3d_rocket.png
  lib/data/dto/response/cogo_application_response.dart
  lib/data/service/application_service.dart
  lib/features/home/apply/view_models/matching_view_model.dart
  lib/features/home/apply/view_models/memo_view_model.dart
  lib/features/home/apply/view_models/schedule_view_model.dart
  lib/features/home/apply/views/matching_screen.dart
  lib/features/home/apply/views/memo_screen.dart
  lib/features/home/apply/views/schedule_screen.dart
Labels: feature

#56 [Feature/캘린더] 멘토 코고 시간 선택 + 컴포넌트 수정
  lib/common/navigator/view_model/bottom_navigation_bar_view_model.dart
  lib/common/widgets/components/basic_button.dart
  lib/common/widgets/components/basic_button2.dart
  lib/common/widgets/components/basic_textfield.dart
  lib/common/widgets/components/custom_box.dart
  lib/common/widgets/components/date_picker.dart
  lib/common/widgets/components/header.dart
  lib/common/widgets/components/tag.dart
  lib/common/widgets/horizontal_button_list.dart
  lib/common/widgets/mentor_profile_reminder_dialog.dart
  lib/common/widgets/multi_selection_time_picker.dart
  lib/common/widgets/single_selection_time_picker.dart
  lib/common/widgets/tag_list.dart
  lib/common/widgets/widgets.dart
  lib/data/di/get_it_locator.dart
  lib/data/dto/request/time_select_request.dart
  lib/data/dto/response/add_possible_date_response.dart
  lib/data/service/possibledate_service.dart
  lib/features/auth/signup/view_models/shared_views/choose_role_view_model.dart
  lib/features/auth/signup/views/mentee/interest_selection_screen.dart
  lib/features/auth/signup/views/mentor/club_selection_screen.dart
  lib/features/auth/signup/views/mentor/interest_selection_screen.dart
  lib/features/auth/signup/views/mentor/mentor_info_screen.dart
  lib/features/auth/signup/views/shared_views/choose_role_screen.dart
  lib/features/auth/signup/views/shared_views/completion_screen.dart
  lib/features/auth/signup/views/shared_views/name_input_screen.dart
  lib/features/auth/signup/views/shared_views/phone_number_screen.dart
  lib/features/cogo/views/mentee/sended_cogo_detail_screen.dart
  lib/features/cogo/views/mentee/sended_cogo_screen.dart
  lib/features/cogo/views/mentee/successed_cogo_detail_screen.dart
  lib/features/cogo/views/mentee/successed_cogo_screen.dart
  lib/features/cogo/views/mentor/received_cogo_detail_screen.dart
  lib/features/cogo/views/mentor/successed_cogo_detail_screen.dart
  lib/features/cogo/views/mentor/successed_cogo_screen.dart
  lib/features/home/apply/views/matching_screen.dart
  lib/features/home/apply/views/memo_screen.dart
  lib/features/home/apply/views/schedule_screen.dart
  lib/features/home/home/view/home_screen.dart
  lib/features/home/mentor_detail/views/mentor_introduction_screen.dart
  lib/features/home/mentor_detail/views/mentor_question1_screen.dart
  lib/features/home/mentor_detail/views/mentor_question2_screen.dart
  lib/features/home/search/view/search_screen.dart
  lib/features/mypage/mentor_time_setting/mentor_time_setting_screen.dart
  lib/features/mypage/mentor_time_setting/mentor_time_setting_view_model.dart
  lib/features/mypage/mypage_screen.dart
  lib/route/routes.dart
  pubspec.yaml
Labels: feature

#59 [Feature/#58] 신청온/성사된 코고 조회 api + cogo탭 mentor, mentee 통합
  lib/constants/paths.dart
  lib/data/dto/response/requested_cogo_response.dart
  lib/data/service/application_service.dart
  lib/domain/entity/requested_cogo_entity.dart
  lib/features/cogo/cogo_screen.dart
  lib/features/cogo/cogo_view_model.dart
  lib/features/cogo/matched_cogo/successed_cogo_detail_screen.dart
  lib/features/cogo/matched_cogo/successed_cogo_detail_view_model.dart
  lib/features/cogo/matched_cogo/successed_cogo_screen.dart
  lib/features/cogo/matched_cogo/successed_cogo_view_model.dart
  lib/features/cogo/models/mentor/received_cogo_item.dart
  lib/features/cogo/unmatched_cogo/requested_cogo_detail_screen.dart
  lib/features/cogo/unmatched_cogo/requested_cogo_detail_view_model.dart
  lib/features/cogo/unmatched_cogo/requested_cogo_screen.dart
  lib/features/cogo/unmatched_cogo/requested_cogo_view_model.dart
  lib/features/cogo/view_models/mentee/cogo_view_model.dart
  lib/features/cogo/view_models/mentee/sended_cogo_detail_view_model.dart
  lib/features/cogo/view_models/mentee/sended_cogo_view_model.dart
  lib/features/cogo/view_models/mentee/successed_cogo_detail_view_model.dart
  lib/features/cogo/view_models/mentee/successed_cogo_view_model.dart
  lib/features/cogo/view_models/mentor/received_cogo_view_model.dart
  lib/features/cogo/view_models/mentor/successed_cogo_view_model.dart
  lib/features/cogo/views/mentee/sended_cogo_detail_screen.dart
  lib/features/cogo/views/mentee/sended_cogo_screen.dart
  lib/features/cogo/views/mentee/successed_cogo_detail_screen.dart
  lib/features/cogo/views/mentor/cogo_screen.dart
  lib/features/cogo/views/mentor/received_cogo_screen.dart
  lib/route/routes.dart
Labels: feature

#38 [Feature/user] 회원가입
  lib/common/enums/interest.dart
  lib/common/enums/role.dart
  lib/common/navigator/view_model/bottom_navigation_bar_view_model.dart
  lib/common/widgets/components/basic_button2.dart
  lib/constants/paths.dart
  lib/data/di/api_client.dart
  lib/data/di/get_it_locator.dart
  lib/data/dto/response/mentee_signup_response.dart
  lib/data/dto/response/mentor_signup_response.dart
  lib/data/dto/response/user_info_response.dart
  lib/data/repository/local/locale_manager.dart
  lib/data/repository/local/secure_storage_repository.dart
  lib/data/service/mentor_service.dart
  lib/data/service/refresh_service.dart
  lib/data/service/user_service.dart
  lib/features/auth/login/login_view_model.dart
  lib/features/auth/signup/agreement/agreement_screen.dart
  lib/features/auth/signup/agreement/agreement_view_model.dart
  lib/features/auth/signup/choose_role/choose_role_screen.dart
  lib/features/auth/signup/choose_role/choose_role_view_model.dart
  lib/features/auth/signup/club/club_selection_screen.dart
  lib/features/auth/signup/club/club_selection_view_model.dart
  lib/features/auth/signup/completion/completion_screen.dart
  lib/features/auth/signup/completion/completion_view_model.dart
  lib/features/auth/signup/interest/interest_selection_screen.dart
  lib/features/auth/signup/interest/interest_selection_view_model.dart
  lib/features/auth/signup/mento_info/mentor_info_screen.dart
  lib/features/auth/signup/mento_info/mentor_info_view_model.dart
  lib/features/auth/signup/name_input/name_input_screen.dart
  lib/features/auth/signup/name_input/name_input_view_model.dart
  lib/features/auth/signup/phone_number/phone_number_screen.dart
  lib/features/auth/signup/phone_number/phone_number_view_model.dart
  lib/features/auth/signup/view_models/mentee/interest_selection_view_model.dart
  lib/features/auth/signup/view_models/mentor/club_selection_view_model.dart
  lib/features/auth/signup/view_models/mentor/interest_selection_view_model.dart
  lib/features/auth/signup/view_models/shared_views/choose_role_view_model.dart
  lib/features/auth/signup/view_models/shared_views/name_input_view_model.dart
  lib/features/auth/signup/views/mentor/interest_selection_screen.dart
  lib/features/home/home/view/home_screen.dart
  lib/features/home/home/view_model/home_view_model.dart
  lib/features/mypage/mypage_screen.dart
  lib/features/mypage/mypage_view_model.dart
  lib/main.dart
  lib/route/routes.dart
Labels: feature

#66 [Fix/#63] 버튼 일관성
  lib/common/widgets/components/basic_box.dart
  lib/common/widgets/components/basic_button.dart
  lib/common/widgets/components/basic_button2.dart
  lib/common/widgets/components/secondary_button.dart
  lib/common/widgets/widgets.dart
  lib/constants/button_size.dart
  lib/features/auth/signup/agreement/agreement_screen.dart
  lib/features/auth/signup/choose_role/choose_role_screen.dart
  lib/features/auth/signup/choose_role/choose_role_view_model.dart
  lib/features/auth/signup/club/club_selection_screen.dart
  lib/features/auth/signup/interest/interest_selection_screen.dart
  lib/features/auth/signup/name_input/name_input_screen.dart
  lib/features/auth/signup/phone_number/phone_number_screen.dart
  lib/features/home/apply/views/matching_screen.dart
  lib/features/home/apply/views/memo_screen.dart
Labels: fix
